### ISSUE TITLE
Unable to play song on viusic app

### ISSUE THREAD

**Issue by Devpratap1212** [haturatu/ViMusic#2]
### Steps to reproduce the bug

Open the app then click on any song then song automatically doesn't play and shows bug

### Expected behavior

Whenever i should click on any song to be played then that song should be played at ones

### Actual behavior

When click on songs then app shows up by noting that the returned video id doen't matches the requested one

### Screenshots/Screen recordings

![Screenshot_2024-10-29-01-48-31-18_6f55a3c4de83481ebdee1685416eed82](https://github.com/user-attachments/assets/cb2d3199-4cc5-45bd-9766-67adf866f997)

### ViMusic version

Vi music version 2024

### Android version

Oppo F17 pro

**Comment by haturatu** [comment]
Thank you. I am currently working on replacing it with another library due to significant changes in the YouTube API that have caused this issue.

**Comment by haturatu** [comment]
I'm experiencing issues with Innertube, which I'm currently using in ViMusic. I'm planning to merge any good improvement proposals if available, but if not, I'm also considering merging another library into ViMusic. If I choose the latter, it will involve significant changes, so it will take time. Right now, I'm in the process of reading and understanding the code of the alternative library.
thanks.

**Comment by haturatu** [comment]
done. https://github.com/haturatu/ViMusic/releases/tag/v1.1.1
